[project]
name = "produto-dados-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "agno>=1.7.0",
    "google-genai>=1.24.0",
    "ollama>=0.5.1",
    "openai>=1.93.0",
    "python-dotenv>=1.1.1",
]
